# Generated by Django 2.1 on 2020-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
