# Generated by Django 2.1 on 2020-08-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_requestlist_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='requesttype',
            field=models.CharField(max_length=100),
        ),
    ]
