# Generated by Django 2.1 on 2020-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200819_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlist',
            name='requesttype',
        ),
        migrations.AddField(
            model_name='requestlist',
            name='requesttype',
            field=models.ManyToManyField(to='app.RequestType'),
        ),
    ]
