# Generated by Django 2.1 on 2020-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200819_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='requesttype',
            field=models.ManyToManyField(related_name='requestlist', to='app.RequestType'),
        ),
    ]
