# Generated by Django 2.1 on 2020-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200819_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='requesttype',
            field=models.ManyToManyField(to='app.RequestType'),
        ),
    ]
