# Generated by Django 2.1 on 2020-08-21 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200820_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 12, 9, 44, 35688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 12, 9, 44, 35688, tzinfo=utc)),
        ),
    ]
