# Generated by Django 2.1 on 2020-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200821_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
